### ISSUE TITLE
bottom of page privacy / terms are wrong links

### ISSUE THREAD

**Issue by G2G2G2G** [LizardByte/LizardByte.github.io#60]
### Describe the Bug

they are missing a directory /
for example:
it is set as https://app.lizardbyte.devprivacy.html
should be https://app.lizardbyte.dev/privacy.html

Terms is also like that. Also on their respective pages the links seem to not be to their page but go back to the main site

### Expected Behavior

link works

**Comment by ReenigneArcher** [comment]
I'm guessing the crowdin JavaScript is screwing with it. The footers are all generated by the same JavaScript code.

The header should be correct. The items in the navbar should point to sections the current page has.
